### ISSUE TITLE
docker-machine deprecation

### ISSUE THREAD

**Issue by fxi** [exoscale/docker-machine-driver-exo#3]
Hi,

It looks like docker-machine is deprecated.

Any tips on an alternative  ? 

Your documentation could be updated, e.g. in

https://www.exoscale.com/syslog/deploy-a-remote-docker-host-and-connect-to-it-using-your-local-docker-client/

Gitlab seems to maintained a fork

https://gitlab.com/gitlab-org/ci-cd/docker-machine

**Comment by greut** [comment]
Hi, (former Exoscale employee)

At the time there was this alternative: https://github.com/machine-drivers

The alternative nowadays is probably [Kubernetes](https://www.exoscale.com/sks/)  or a simple `cloud-init` doing `curl -sfL https://get.k3s.io | sh -`

**Comment by pyr** [comment]
Hi @fxi,

I suppose it depends on what your intent is. If you wish to deploy a single container to machines in order to expose a single service over the internet, [Container Optimized Instances](https://www.exoscale.com/syslog/container-optimized-instances/) could be the way to go.

As @greut points out, if you wish to interact with deployments, [SKS](https://www.exoscale.com/sks/) would be the way to go.

I hope this helps, cheers

**Comment by fxi** [comment]
Thanks !

So, we used docker-machine + docker swarm + a single script to create a cluster and provision everything. Then, a docker-compose file to configure all services.  We also have a portainer instance to quickly visualize everything. Extremely convenient for the whole team.

I have probably bet on the wrong horse, but we will adapt. Why not use SKS.. 

Have a nice day !

**Comment by pyr** [comment]
> I have probably bet on the wrong horse, but we will adapt. Why not use SKS..

Yep we had to make a choice and for better or worse the largest traction by far is behind Kubernetes. It's definitely a step up from swarm in terms of overall ability, but also in complexity. Portainer claims to support it though so hopefully there is a smooth transition from this PoV

**Comment by pyr** [comment]
The documentation has been fixed on the relevant blog posts, thanks for raising the issue!
